
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 10 09:43:39 CET 2017
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 27;
  public static final int EGAL = 15;
  public static final int OU = 13;
  public static final int CLASS = 16;
  public static final int PLUS = 2;
  public static final int SUP = 8;
  public static final int STATUT = 25;
  public static final int ECR = 19;
  public static final int VIRGULE = 6;
  public static final int NON = 14;
  public static final int PARFER = 21;
  public static final int MOINS = 3;
  public static final int INF = 9;
  public static final int POINTVIRGULE = 7;
  public static final int TYPE = 26;
  public static final int ENTIER = 17;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int EGALEGAL = 10;
  public static final int DIV = 5;
  public static final int CONSTANTEBOOL = 23;
  public static final int ET = 12;
  public static final int error = 1;
  public static final int PAROUV = 20;
  public static final int CONSTANTECHAINE = 24;
  public static final int DIFF = 11;
  public static final int CONSTANTEINT = 22;
  public static final int FIN = 18;
}

